import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';

import Header from '../../components/header';
import Navbar from '../../components/Navbar';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        {/* bootstrap */}
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous"
        />

        {/* fontawsome */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        />

        {/* bootstrap-datepickerを読み込む */}
        <link
          rel="stylesheet"
          type="text/css"
          href="../bootstrap-datepicker-1.6.4-dist/css/bootstrap-datepicker.min.css"
        />
        <script
          type="text/javascript"
          src="../bootstrap-datepicker-1.6.4-dist/js/bootstrap-datepicker.min.js"
        ></script>
        <script
          type="text/javascript"
          src="../bootstrap-datepicker-1.6.4-dist/locales/bootstrap-datepicker.ja.min.js"
        ></script>

      </Head>

      <main className={styles.main}>
        <Navbar></Navbar>
        <div class="m-auto container">
          <Header></Header>

          {/* datapicker */}
          <section>
            <div class="container">
                {/* day-selecter start */}
                <div class="row">
                  <div class="col-6 m-auto">
                    {/* ここにカレンダー表示用のテキストボックスを追加 */}
                    <input type="text" class="form-control" id="date_sample" />
                  </div>
                  {/* bootstrap-datepickerのjavascriptコード */}
                  <script>
                    $('#date_sample').datepicker();
                    </script>
                  {/* day-selecter end */}
              </div>
            </div>
          </section>

          {/* highlight start */}
            {/* data highlight start */}
            <div class="d-flex justify-content-center text-center">
              <section class="day-highlight col-12 mb-3">
                <div class="d-flex justify-content-end">
                  <button class="btn">+ edit weight record</button>
                </div>
                  <ul class="row justify-content-center d-flex mb-5">
                    <div class="m-4 col-4" className={styles.highlight_item}>
                      <p class="pt-3">体重</p>
                      <div class="m-5">
                        <p>over</p>
                        <h2>1.0</h2>
                      </div>
                      <p>50 / 49 kg</p>
                    </div>
                    <div class="m-4 col-4" className={styles.highlight_item}>
                      <p class="pt-3">摂取可能カロリー</p>
                      <div class="m-5">
                        <p>over</p>
                        <h2>876</h2>
                      </div>
                      <p>2276 / 1400 kcal</p>
                    </div>
                    <div class="m-4 col-4" className={styles.highlight_item}>
                      <p class="pt-3">燃焼</p> 
                      <div class="m-5">
                        <p>under</p>
                        <h2>120</h2>             
                        </div>
                      <p>130 / 250 kcal</p>
                    </div>
                  </ul>

                <div class="row mb-5">
                  <div class="col-4">
                    <p>炭水化物</p>
                    <div class="progress mb-2">
                      <div class="progress-bar" role="progressbar" style={{width: "25%"}} aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">25%</div>
                    </div>
                    <p>0 / 145 g</p>
                  </div>
                  <div class="col-4">
                    <p>タンパク質</p>
                    <div class="progress mb-2">
                      <div class="progress-bar" role="progressbar" style={{width: "25%"}} aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">25%</div>
                    </div>              <p>0 / 145 g</p>
                  </div>
                  <div class="col-4">
                    <p>脂質</p>
                    <div class="progress mb-2">
                      <div class="progress-bar" role="progressbar" style={{width: "25%"}} aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">25%</div>
                    </div>
                    <p>0 / 145 g</p>
                  </div>
                </div>
              </section>
            </div>
            {/* data highlight end */}

            {/* food-highlight start */}
            <section class="food-highlight">
              <div class="row">
                <h4 class="col-10">Total : 2276 kcal</h4>
                <button class="btn col-2 m-auto">+ add food record</button>
              </div>
              <div className={styles.foodpic__highlight}>
                <div class="m-2" className={styles.card} style={{width: "18rem"}}>
                  <img src="./images/foodIMG_01.jpg" class="card-img-top" alt="..." />
                  <div class="card-body">
                    <h5 class="card-title">朝食</h5>
                    <h4 class="card-text"><small>489</small> / 569kcal</h4>
              
                      {/* Button trigger modal */}
                      <div class=" text-right">
                        <button type="button" class="btn btn-primary mt-2 px-4" data-toggle="modal" data-target="#testModal">view</button>
                      </div>
                  </div>
                </div>
                <div class="m-2" className={styles.card} style={{width: "18rem"}}>
                  <img src="./images/foodIMG_01.jpg" class="card-img-top" alt="..." />
                  <div class="card-body">
                    <h5 class="card-title">昼食</h5>
                    <h4 class="card-text"><small>489</small> / 569kcal</h4>

                      <div class=" text-right">
                        <button type="button" class="btn btn-primary mt-2 px-4" data-toggle="modal" data-target="#testModal">view</button>
                      </div>
                  </div>
                </div>
                <div class="m-2" className={styles.card} style={{width: "18rem"}}>
                  <img src="./images/foodIMG_01.jpg" class="card-img-top" alt="..." />
                  <div class="card-body">
                    <h5 class="card-title">夕食</h5>
                    <h4 class="card-text"><small>489</small> / 569kcal</h4>

                      <div class=" text-right">
                        <button type="button" class="btn btn-primary mt-2 px-4" data-toggle="modal" data-target="#testModal">view</button>
                      </div>
                  </div>
                </div>
                <div class="m-2" className={styles.card} style={{width: "18rem"}}>
                  <img src="./images/foodIMG_01.jpg" class="card-img-top" alt="..." />
                  <div class="card-body">
                    <h5 class="card-title">間食1</h5>
                    <h4 class="card-text"><small>489</small> / 569kcal</h4>
              
                      <div class=" text-right">
                        <button type="button" class="btn btn-primary mt-2 px-4" data-toggle="modal" data-target="#testModal">view</button>
                      </div>
                  </div>
                </div>
                <div class="m-2" className={styles.card} style={{width: "18rem"}}>
                  <img src="./images/foodIMG_01.jpg" class="card-img-top" alt="..." />
                  <div class="card-body">
                    <h5 class="card-title">間食2</h5>
                    <h4 class="card-text"><small>489</small> / 569kcal</h4>

                      <div class=" text-right">
                        <button type="button" class="btn btn-primary mt-2 px-4" data-toggle="modal" data-target="#testModal">view</button>
                      </div>
                  </div>
                </div>
                
                
              </div>

              {/* modal button クリック後に表示される画面の内容 start*/}
              <div class="modal fade" id="testModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
                <div class="modal-dialog modal-dialog-scrollable">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="myModalLabel">朝食　詳細</h4>
                        </div>
                        <div class="modal-body">
                            <img src="./img/foodIMG_01.jpg" alt="" />
                        
                            <table class="table my-5">
                              <thead>
                                <tr>
                                  <th scope="col">#</th>
                                  <th scope="col">栄養成分       </th>
                                  <th scope="col">量</th>
                                </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  <th scope="row">1</th>
                                  <td>カロリー</td>
                                  <td>0 <small>kcal</small></td>
                                </tr>
                                <tr>
                                  <th scope="row">2</th>
                                  <td>炭水化物</td>
                                  <td>0.0 <small>g</small></td>
                                </tr>
                                <tr>
                                  <th scope="row">3</th>
                                  <td>タンパク質</td>
                                  <td>0.0 <small>g</small></td>
                                </tr>
                                <tr>
                                  <th scope="row">3</th>
                                  <td>脂質</td>
                                  <td>0.0 <small>g</small></td>
                                </tr>
                              </tbody>
                            </table>

                            <table class="table my-5">
                              <thead>
                                <tr>
                                  <th scope="col">#</th>
                                  <th scope="col">その他</th>
                                  <th scope="col">量</th>
                                </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  <th scope="row">1</th>
                                  <td>コレステロール</td>
                                  <td>0 <small>kcal</small></td>
                                </tr>
                                <tr>
                                  <th scope="row">2</th>
                                  <td>ナトリウム</td>
                                  <td>0.0 <small>g</small></td>
                                </tr>
                                <tr>
                                  <th scope="row">3</th>
                                  <td>塩分</td>
                                  <td>0.0 <small>g</small></td>
                                </tr>
                                <tr>
                                  <th scope="row">4</th>
                                  <td>水</td>
                                  <td>0.0 <small>g</small></td>
                                </tr>
                                <tr>
                                  <th scope="row">5</th>
                                  <td>アルコール</td>
                                  <td>0.0 <small>g</small></td>
                                </tr>
                              </tbody>
                            </table>

                            <table class="table my-5">
                              <thead>
                                <tr>
                                  <th scope="col">#</th>
                                  <th scope="col">ビタミン</th>
                                  <th scope="col">量</th>
                                </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  <th scope="row">1</th>
                                  <td>ビタミンB7</td>
                                  <td>0.0 <small>g</small></td>
                                </tr>
                                <tr>
                                  <th scope="row">2</th>
                                  <td>ビタミンC</td>
                                  <td>0.0 <small>g</small></td>
                                </tr>
                                <tr>
                                  <th scope="row">3</th>
                                  <td>ビタミンD</td>
                                  <td>0.0 <small>g</small></td>
                                </tr>
                                <tr>
                                  <th scope="row">4</th>
                                  <td>ビタミンE</td>
                                  <td>0.0 <small>g</small></td>
                                </tr>
                                <tr>
                                  <th scope="row">5</th>
                                  <td>ビタミンK</td>
                                  <td>0.0 <small>g</small></td>
                                </tr>
                              </tbody>
                            </table>

                          <table class="table my-5">
                              <thead>
                                <tr>
                                  <th scope="col">#</th>
                                  <th scope="col">ミネラル</th>
                                  <th scope="col">量</th>
                                </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  <th scope="row">1</th>
                                  <td>カリウム</td>
                                  <td>0.0 <small>g</small></td>
                                </tr>
                                <tr>
                                <th scope="row">2</th>
                                <td>カルシウム</td>
                                <td>0.0 <small>g</small></td>
                              </tr>
                              <tr>
                                <th scope="row">3</th>
                                <td>マグネシウム</td>
                                <td>0.0 <small>g</small></td>
                              </tr>
                              <tr>
                                <th scope="row">4</th>
                                <td>亜鉛</td>
                                <td>0.0 <small>g</small></td>
                              </tr>
                              <tr>
                                <th scope="row">5</th>
                                <td>鉄</td>
                                <td>0.0 <small>g</small></td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
                            <button type="button" class="btn btn-danger">データ削除</button>
                        </div>
                    </div>
                </div>
              </div>
              {/* modal button クリック後に表示される画面の内容 end */}
            </section>
            {/* food-highlight end */}
          {/* highlight end */}
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
